spring:
  application:
      name: cloudBusDemo
      index: ${random.uuid} # this ensures that our applicationId is unique
  cloud:
    stream: 
      kafka:
        binder:
          zkNodes: localhost:2181
          brokers: localhost:9092
          zkSessionTimeout: 60000
    
server:
    port: 9440